# Generated by Django 5.2.12 on 2026-03-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_orden_orderproduct_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
