# Generated by Django 5.2.12 on 2026-03-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_orderprice"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderPrice",
        ),
    ]
